### PR TITLE
Reconnect to OSCAM if an error was received (fixes an issue when usin…

### PR DESCRIPTION
**Pull request by ua0lnj**
…g an adapter offset if one of the clients is disconnected).

### CODE REVIEW

**Comment by ua0lnj** [comment]
Start 1 vdr, test encrypt channels.
Start 2 vdr, test encrypt channels.
Select free channel on 1 vdr.
Select free channel on 2 vdr.
Stop 2 vdr.
Select encrypt channel on 1 vdr. No decoding. Error of dvbapi in log.
The 2 vdr close all connection on oscam then exited.
The 1 vdr need reconnecting to oscam.

**Comment by haarm** [comment]
Do you use the parameter -0 ?

**Comment by manio** [comment]
@ua0lnj Thanks, is it ok to merge regarding @haarm comment?

**Comment by ua0lnj** [comment]
Yes. Example.
1 vdr -o2.
2 vdr -o8.
You will get the same effect if:
1- vdr -o2
2- TVH (can't -o options)

**Comment by haarm** [comment]
I also use 4 VDRs with dvbapi and have no problems

**Comment by ua0lnj** [comment]
You try stop vdr? If all vdr works, no problems.

**Comment by ua0lnj** [comment]
I tested des keys with disabled extended cw, and have same result.
When I turn off the second client, the first one stops working.
Latest oscam.

**Comment by manio** [comment]
This PR looks fine for me, merging, thanks @ua0lnj

**Pull request merged**
